### ISSUE TITLE
NCLL error

### ISSUE THREAD

**Issue by mrsempress** [facebookresearch/NeRF-Det#7]
I got NCLL error both in one gpu and multi gpus. For one gpu, it occurs in model.cuda(); for multi gpus, it occurs in self.backbone.init_weights(pretrained=pretrained).

The log is as follows:
```
2023-08-22 19:18:20,402 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /mnt/lustre/share/cuda-10.1/
NVCC: Cuda compilation tools, release 10.1, V10.1.168
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=com$
ute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK $
DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign$
compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarat$
ons -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitial$
zed -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLO$
=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.8.0
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.10.0
MMDetection3D: 0.8.0+8684e1f
------------------------------------------------------------

2023-08-22 19:18:20,402 - mmdet - INFO - Distributed training: True
2023-08-22 19:18:21,312 - mmdet - INFO - Config: (...)

2023-08-22 19:18:21,312 - mmdet - INFO - Set random seed to 0, deterministic: False
2023-08-22 19:18:21,913 - mmdet - INFO - load model from: torchvision://resnet50
2023-08-22 19:18:21,913 - mmdet - INFO - Use load_from_torchvision loader
```

**Comment by mrsempress** [comment]
Maybe it is because of this warning:
```
/mnt/lustre/huangchenxi/anaconda3/envs/nerfdet/lib/python3.7/site-packages/torch/cuda/__init__.py:125: UserWarning: 
NVIDIA A100-SXM4-80GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA A100-SXM4-80GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```
But how to solve it?

**Comment by mrsempress** [comment]
And for the dockerfile, I got the error below:
```
Reading package lists...
W: GPG error: https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
The command '/bin/sh -c apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by chenfengxu714** [comment]
Hi, have you tried upgrade you cuda version, cuda10.1 might be too old to be compatible to mmdet3d.

**Comment by mrsempress** [comment]
I tried cuda 11.3/11.0, but both failed in training time. As for cuda 10.1, I reference the guidance you provided in [dockerfile](https://github.com/facebookresearch/NeRF-Det/blob/8684e1f856d3005754c4eed8c0a4e6b1b1ab4948/docker/Dockerfile#L12C3-L12C3).

**Comment by chenfengxu714** [comment]
Could you show me what your error is when you use cuda 11.3/11.0 during training.

**Comment by mrsempress** [comment]
The version of mmcv is 1.2.7, using `pip install mmcv-full==1.2.7 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.1/index.html`.
And the version of mmdet is 2.10.0,  the version of mmengine is 0.8.4.
```
Traceback (most recent call last):
  File "tools/train.py", line 15, in <module>
    from mmdet3d.datasets import build_dataset
  File "/mnt/petrelfs/huang/NeRF-Det/mmdet3d/datasets/__init__.py", line 1, in <module>
    from mmdet.datasets.builder import build_dataloader
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/datasets/cityscapes.py", line 16, in <module>
    from .coco import CocoDataset
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/datasets/coco.py", line 14, in <module>
    from mmdet.core import eval_recalls
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv
/mnt/lustre/huang/anaconda3/envs/nerfdet/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 259555) of binary: /mnt/lustre/huang/anaconda3/envs/nerfdet/bin/python3
```

**Comment by chenfengxu714** [comment]
Hi, I am not sure why the issue occurs but I searched it for a while, here are two possible solutions, could you have a try?
https://github.com/open-mmlab/mmdetection/issues/4291
https://github.com/open-mmlab/mmdetection3d/issues/1152

**Comment by mrsempress** [comment]
I have also seen these issues before. But I installed the pytorch/torchvision/cuda by the command from https://pytorch.org/get-started/previous-versions/. So, it didn't work for me.

**Comment by rahulswa08** [comment]
I'm facing the same issue.  did you find any solution to this?

I'm running on docker image from `pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel`

@mrsempress @chenfengxu714

**Comment by vinleeit** [comment]
> And for the dockerfile, I got the error below:
> 
> ```
> Reading package lists...
> W: GPG error: https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
> E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
> The command '/bin/sh -c apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
> ```

Hey @mrsempress, you can refer to this forum: [Invalid public key for CUDA apt repository](https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901) for this issue. I followed [user22187's suggestion](https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901/21).

Thus, I added an additional line into the dependency installation section:

```bash
apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
```

Updated section:

```dockerfile
RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-get update \
    && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```
