### ISSUE TITLE
Do I need to download the wholes scannet dataset (1.2 T)?

### ISSUE THREAD

**Issue by yyfz** [facebookresearch/NeRF-Det#8]

**Comment by chenfengxu714** [comment]
Yes, please do so as indicated by https://github.com/SamsungLabs/imvoxelnet/tree/master/data/scannet.

**Comment by chenfengxu714** [comment]
No, you do not need to do so.

**Comment by yyfz** [comment]
> No, you do not need to do so.

So we only use 300 images per scene for training, am I right?

**Comment by chenfengxu714** [comment]
yes

**Comment by yyfz** [comment]
Hi, I follow https://github.com/SamsungLabs/imvoxelnet/tree/master/data/scannet to download scannet dataset and it seems that I miss the extrinsic matrix. I get error: "extrinsic=input_dict['lidar2img'], KeyError: 'lidar2img'".

I'm sorry to bother you. I'm a beginner in 3D vision, and I'm having difficulty running your code. Hope you can give me a help :)

**Comment by Yanyirong** [comment]
Hi @yyfz 
Have you successfully download the dataset?I wonder how to deal with the dataset.Do I need to download the whole 1.2T dataset first and then extract?Actually I do not have enough space now so I hope to get your help (´･ᆺ･`)

**Comment by yyfz** [comment]
> Hi @yyfz Have you successfully download the dataset?I wonder how to deal with the dataset.Do I need to download the whole 1.2T dataset first and then extract?Actually I do not have enough space now so I hope to get your help (´･ᆺ･`)

Yep, this model need 300 color image and depth map per scene and there are 1700+ scenes. You can download on your server or use a portable storage device.

**Comment by chenfengxu714** [comment]
> Hi, I follow https://github.com/SamsungLabs/imvoxelnet/tree/master/data/scannet to download scannet dataset and it seems that I miss the extrinsic matrix. I get error: "extrinsic=input_dict['lidar2img'], KeyError: 'lidar2img'".
> 
> I'm sorry to bother you. I'm a beginner in 3D vision, and I'm having difficulty running your code. Hope you can give me a help :)

No worry. Do you run 
python tools/create_data.py scannet --root-path ./data/scannet --out-dir ./data/scannet --extra-tag scannet

**Comment by Rorsc4achhh** [comment]
Hi @chenfengxu714 , I'm just wondering that if I want to use NeRF-Det-R50's checkpoint and config file, and try to detect my own scene, how do I prepare the "ScanNetMultiViewDataset" ? Maybe it's because my own carelessness, I didn't find any info about it. 
About the "posed RGB images" that NeRF-Det needs, is it ok that I arrange my input data with images and a transforms.json file in a folder as data_root (output from colmap, image frames with camera poses)?

And also just wanna make sure that is this the correct way to detect a scene by using test.py? 
python tools/test.py configs/nerfdet/nerfdet_res50_2x_low_res.py     work_dirs/nerfdet_res50_2x_low_res/latest.pth --show     --show-dir work_dirs/nerfdet_res50_2x_low_res

**Comment by yyfz** [comment]
Hi @chenfengxu714 , now I get the error msg about dataset as follows:
-------------------------------------------------------------------------
Original Traceback (most recent call last):
  File "/mnt/workspace/wangyifan/miniconda3/envs/nerf-det/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/workspace/wangyifan/miniconda3/envs/nerf-det/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/workspace/wangyifan/miniconda3/envs/nerf-det/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/workspace/wangyifan/miniconda3/envs/nerf-det/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 151, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/mnt/workspace/wangyifan/master/NeRF-Det-main/mmdet3d/datasets/custom_3d.py", line 308, in __getitem__
    data = self.prepare_train_data(idx)
  File "/mnt/workspace/wangyifan/master/NeRF-Det-main/mmdet3d/datasets/custom_3d.py", line 161, in prepare_train_data
    input_dict = self.get_data_info(index)
  File "/mnt/workspace/wangyifan/master/NeRF-Det-main/mmdet3d/datasets/scannet_monocular_dataset.py", line 17, in get_data_info
    info = self.data_infos[index]
KeyError: 1

It seems like an error of Scannet dataset structure or the .pkl file. I have followed https://github.com/SamsungLabs/imvoxelnet/tree/master/data/scannet and prepared the data like:
-data/scannet
|--instance_mask
|--meta_data
|--points
|--posed_images
|--scannet_instance_data
|--scans
|--seg_info
|--semantic_mask
|--scannet_infos_test.pkl
|--scannet_infos_train.pkl
|--scannet_infos_val.pkl
|--scannet_utils.py

Sorry to bother again!

**Comment by chenfengxu714** [comment]
Hi, no worry. It is a little bit tricky to customize your own dataloader under the mmdetection3D library. You should prepare camera intrinsics, extrinsics, and RGB images and you should modify ScanNetMultiViewDataset to form line 54 and line 61.  So simply say, the most important items are to form input_dict with your own data.

**Comment by Rorsc4achhh** [comment]
> Hi, no worry. It is a little bit tricky to customize your own dataloader under the mmdetection3D library. You should prepare camera intrinsics, extrinsics, and RGB images and you should modify ScanNetMultiViewDataset to form line 54 and line 61. So simply say, the most important items are to form input_dict with your own data.

@chenfengxu714 Thanks for your reply. Is it possible that I prepared my own data in Scannet format? which is more convenient.

**Comment by hollow-503** [comment]
> Yes, please do so as indicated by https://github.com/SamsungLabs/imvoxelnet/tree/master/data/scannet.

Hi @chenfengxu714, 
Thanks for your patient reply. I follow the tutorials to download scannet dataset. 
"In this directory, extract point clouds and annotations by running python batch_load_scannet_data.py. Add the `--max_num_point 50000` flag if you only use the ScanNet data for the detection task. It will downsample the scenes to less points."
Here, should I add `--max_num_point 50000` to downsample the scenes? I am new in Nerf, and I don't know whether it will influence the perfomance of the detection branch.

**Comment by hollow-503** [comment]
> > Hi @yyfz Have you successfully download the dataset?I wonder how to deal with the dataset.Do I need to download the whole 1.2T dataset first and then extract?Actually I do not have enough space now so I hope to get your help (´･ᆺ･`)
> 
> Yep, this model need 300 color image and depth map per scene and there are 1700+ scenes. You can download on your server or use a portable storage device.

Hi @yyfz,
Here, should you add `--max_num_point 50000` to downsample the scenes when preparing the Scannet dataset as mentioned in [mmdet3d](https://github.com/open-mmlab/mmdetection3d/blob/1.0/data/scannet/README.md)?
